services:
  - type: web
    name: barry-discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false